package de.toengi.cili.model.enums;

public enum ProcessingJobType {
    THUMBNAIL, OCR, PREVIEW, TRANSCODE,
    VIDEO_ANALYSIS, VIDEO_TRANSCODE, WAV_EXTRACT, WHISPER_TRANSCRIBE,
    AUDIO_NORMALIZE, SUBTITLE_TRANSLATE, DOCUMENT_TRANSLATE, OLLAMA_ANALYSIS,
    TELEGRAM_IMPORT, VIDEO_URL_IMPORT, VIDEO_CLIP, TESTIMONIAL_SUMMARY
}
